### ISSUE TITLE
Broken link to Katello Release Notes

### ISSUE THREAD

**Issue by Areyus** [theforeman/foreman-documentation#1064]
From the menu, clicking on "Katello on EL" -> "Release Notes" results in a "Page not found" error.
This link should probably point to [the Katello CHANGELOG.md](https://github.com/Katello/katello/blob/KATELLO-4.3/CHANGELOG.md) for each respective version.

**Comment by ekohl** [comment]
For which version are you looking, because it's there for nightly, 3.0 and 3.1. However, it isn't for 2.5 and 2.4. That's because the site can't differentiate between versions. That also makes this hard to deal with.

**Comment by Areyus** [comment]
I was in fact looking at the 2.5 docs at that moment. I assumed this was a general problem, but it looks like I just misread the menu at that point. Everything 3.0 and upwards work on my side, too.

**Comment by ekohl** [comment]
Yes, that's a limitation. We have [nav.js](https://github.com/theforeman/foreman-documentation/blob/master/web/content/js/nav.js) and as you can see, there's no list per version. That's still something we need to resolve.

The release notes guide is a relative new addition and wasn't ported back to unsupported versions. As the author of that guide, I'd welcome feedback.

**Comment by Areyus** [comment]
OK, I see now where this comes from. Maybe it would be a good idea to at least make a dummy page with links to the old changelog pages, if the framework allows for that? This would at least be better than leading people to a site not found error imho.

Some feedback as a side note: I really like having the release notes of both Katello and Foreman packaged into one easily accessible page. This makes looking up the changelog in preparation for updates much more convenient.

**Comment by ekohl** [comment]
> OK, I see now where this comes from. Maybe it would be a good idea to at least make a dummy page with links to the old changelog pages, if the framework allows for that? This would at least be better than leading people to a site not found error imho.

A dummy with a short "there is no changelog" is actually a good idea.

> Some feedback as a side note: I really like having the release notes of both Katello and Foreman packaged into one easily accessible page. This makes looking up the changelog in preparation for updates much more convenient.

That was exactly my goal. I chose to keep Foreman and Katello releases chronological and I do wonder if that is clear (and helps).

**Comment by Areyus** [comment]
>  I chose to keep Foreman and Katello releases chronological and I do wonder if that is clear (and helps).
At least to me, this was clear. Although I might have just gotten used to it after years of reading Foreman and Katello changelogs which have (to my memory) always been structured like this. I believe this is a useful and clear structure as it is.
