### ISSUE TITLE
GHA deploy action does not clean old directories

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1086]
URL I found: https://docs.theforeman.org/nightly/Installing_Server_on_Red_Hat/index-foreman-el.html < still contains `_on_Red_Hat`. See also https://github.com/theforeman/foreman-documentation/commit/de2b45611231fb091644e350424f86a88791640b
(found it on https://docs.theforeman.org/nightly.html).

My expectation: https://docs.theforeman.org/nightly/Installing_Server/index-foreman-el.html < `doc-Installing_Server` is our "current" directory for this guide.

I am unsure what's to do, but I imagine we need to adapt the navigation to reflect the "no OS" change and ensure when we deploy to docs.theforeman.org that all old files are gone.

Both "variants" are online which makes we wonder where things went south.

**Comment by lzap** [comment]
Removed the two offending directories:

To github.com:theforeman/foreman-documentation
   d16dca69..2bebfb70  gh-pages -> gh-pages

**Comment by maximiliankolb** [comment]
Thanks!
