### ISSUE TITLE
Better book titles upstream

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#111]
On our front page we currently have:

* Installing Foreman on RHEL/CentOS
* Installing Smart Proxy on RHEL/CentOS
* Installing Foreman on Debian/Ubuntu
* Installing Smart Proxy on Debian/Ubuntu 

https://docs.theforeman.org/web/

But when you open these it reads e.g. "Installing Foreman server from a Connected Network". We should probably change these titles to match the front page or come up with something that works fine.

**Comment by melcorr** [comment]
Directory names have been updated as part of #114
