### ISSUE TITLE
Debian installation docs mention Katello requirements

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#112]
https://docs.theforeman.org/guides/build/doc-Installing_Capsule_Server/index-foreman-deb.html lists some services that are not relevant.
* postgres
On EL7 this is because of Pulpcore (Pulp 3), not relevant on Debian
* mongodb
On EL7 this is because of Pulp 2, not relevant on Debian
* apache
On EL7 this is because of a reverse proxy setup for RHSM, not relevant on Debian
* tomcat
This isn't true for any capsule and in particular not for Debian. Tomcat is only used for Candlepin
* foreman
This isn't true for any capsule
* foreman-proxy
This one is true :)
* qpidd
On EL7 this is because of Pulp 2, not relevant on Debian
* qdrouterd
On EL7 this is because of Pulp 2, not relevant on Debian
* squid
On EL7 this is because of Pulp 2, not relevant on Debian
* puppet
This is optional on any setup, but currently installed by default in every scenario. If you want to be precise, we have both `puppet` and `puppetserver` processes.

**Comment by ekohl** [comment]
Looking a bit further down the list, it may be useful to know that what downstream calls a capsule, upstream calls foreman_proxy_content. This concept does not exist on Debian. There we only have Foreman Proxy with its optional services. I still need to rework it into a blog, but on https://cfp.cfgmgmtcamp.be/2020/talk/ZEW3FP/ there's my slides attached (https://cfp.cfgmgmtcamp.be/media/foreman-architecture-to-2.0-and-beyond.pdf). On slide 18 you can see the picture. I now realize that technically that's not entirely correct since Debian doesn't have a standalone `smart_proxy_dynflow_core` process but it runs inside the smart-proxy process if you install the dynflow plugin.

**Comment by melcorr** [comment]
Thanks @ekohl - I am very glad of your help with this. I will implement these changes. I have someone lined up to do a review of the Debian guide - but it is far from ready - no file paths are correct for Debian yet, nor are any of the commands verified.

**Comment by melcorr** [comment]
This is now fixed
