### ISSUE TITLE
Convert2RHEL - add steps how to run role from command line

### ISSUE THREAD

**Issue by stejskalleos** [theforeman/foreman-documentation#1138]
Extend the docs introduced in https://github.com/theforeman/foreman-documentation/pull/1047 with steps how to run the Ansible role from the command line.

**Comment by ianf77** [comment]
When you have the steps sorted out, let me know and I'll create the documentation.

**Comment by ekohl** [comment]
@stejskalleos is this still relevant?

**Comment by apinnick** [comment]
Closing this issue because it is already documented in [Managing hosts](https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#converting-a-host-to-rhel_managing-hosts).
