### ISSUE TITLE
Missing link to "Configuring Hosts Using Puppet"

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1146]
Hi!

[docs.theforeman.org/nightly.html](https://docs.theforeman.org/nightly.html) is missing a link to the standalone Puppet guide: https://docs.theforeman.org/nightly/Managing_Configurations_Puppet/index-foreman-el.html

On [docs.theforeman.org/release/nightly](https://docs.theforeman.org/release/nightly/) however, there are three links with identical names. I don't know where this comes from or how to fix it.

I also don't know the difference between https://docs.theforeman.org/release/nightly/ & https://docs.theforeman.org/nightly.html and at this point, I'm too afraid to ask.

**Comment by lzap** [comment]
That nightly.html is a leftover, removed!

**Comment by maximiliankolb** [comment]
Thank you!
