### ISSUE TITLE
Encapsulate Red Hat-only items in ifdef::satellite[]

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1178]
A lot of code blocks, repo names, etc. assume that the product is Red Hat Satellite, not Foreman/Katello. It would be nice to go through everything and encapsulate content that is only relevant for downstream products, for example using `ifdef::satellite[]` or `ifdef::orcharhino[]` **and** provide alternatives for either everything else, or for the other downstream product and upstream separately.

```
ls -1 guides/common/modules | wc -l
     775
```

Yes, it's a lot of work, 🤷 

This came up in an unrelated PR: https://github.com/theforeman/foreman-documentation/pull/1162#discussion_r830825968

**Comment by maximiliankolb** [comment]
Starting with 3.1, if something like this happens in either the content management guide, the provisioning guide, or the managing hosts guide, then it's basically a bug in orcharhino documentation and I will hopefully spot it 🤞  & create a PR. But I am still working on the process of not only adding non-RHEL OS and non-Satellite specific blocks, but also adding DEB content where yum content is mentioned.

**Comment by ekohl** [comment]
@maximiliankolb any idea how much of this is still relevant?

**Comment by maximiliankolb** [comment]
It _should_ no longer be an issue; as mentioned above, I treat everything as a bug & open a PR if I spot something in managing content/provisioning hosts/managing hosts.
