### ISSUE TITLE
Deprecate EL7 from nightly and Foreman 3.4

### ISSUE THREAD

**Issue by upadhyeammit** [theforeman/foreman-documentation#1217]
- [ ] https://github.com/theforeman/foreman-documentation/pull/1218
- [ ] https://github.com/theforeman/foreman-documentation/pull/1215
- [ ] https://github.com/theforeman/foreman-documentation/pull/1222
- [ ] https://github.com/theforeman/foreman-documentation/pull/1223
- [ ] https://github.com/theforeman/foreman-documentation/pull/1224
- [ ] https://github.com/theforeman/foreman-documentation/pull/1225

**Comment by upadhyeammit** [comment]
The milestone for this effort has been changed. We are planning to start on this on branching 3.3 or by GA of 3.3, with this EL7 deprecation moved to Foreman 3.4.

I have raised https://github.com/theforeman/foreman-documentation/pull/1235 to revert the changes accordingly.

**Comment by ekohl** [comment]
Instead of an issue tracking various tasks I've created https://github.com/theforeman/foreman-documentation/milestone/2 and will close this.
