### ISSUE TITLE
Image files cleanup

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#1261]
The cleanup should encompass:

1. Moving images from guide folders to `common/images`
2. Renaming files to follow a convention so that they are distinguishable per product and make the file names descriptive
3. Updating include paths accordingly

We should agree on a naming convention for image files. [guides/README](https://github.com/theforeman/foreman-documentation/blob/master/guides/README.md) says:
> Image file names use dashes (`-`) and suffix a build target, e.g. `foreman`.

However, we started using prefix instead of suffix. I would suggest suffix so that the same image is "grouped" by topic when sorted alphabetically, which is more benefical for upstream workflow. And do we want to use dashes or underscores? I don't see reasons to prefer one or the other, but we should stick with one.

I guess this will have to be done manually.

**Comment by Lennonka** [comment]
@maximiliankolb I'd love to have your input! :)

**Comment by ekohl** [comment]
Just some infrastructure considerations. Don't let that hold you back too much, but take them into account.

> Moving images from guide folders to `common/images`

I do have a concern that the images end up in every single guide. That makes the gh-pages branch even larger than it is today. I'd love to see some deduplication here, but right now I'm not sure how to achieve that. Perhaps with symlinks or some smarter solution.

> Renaming files to follow a convention so that they are distinguishable per product and make the file names descriptive

I love conventions, but we shouldn't forget to clean the old images from the `gh-pages` branch (or figure out a solution to automatically purge old files on deployment).

**Comment by maximiliankolb** [comment]
It's not really something that I have currently on my plate, but collecting *all* images in one folder seems like a good idea to me; I'd help/support doing that. This could also contain some manual deduplication.

Also, SVGs are generally smaller than PNG files.

Maybe not smylink the "common images" dir to every guide, but instead traverse back `../` to the "common images" dir?

**Comment by Lennonka** [comment]
@ekohl Could we pull the renamed/deleted files from git to update/purge them on deploy? Not sure how to implement it, but git (commits) has the relevant data to do that kind of update, doesn't it?

**Comment by Lennonka** [comment]
@maximiliankolb How would that help us to use backward paths instead of the symlinks? Additionally, I'm not sure how backward paths behave in our downstream build. I'm worried that the symlinks are there for a reason.

**Comment by ekohl** [comment]
I've looked at that, but this would require some tweaking:
https://github.com/theforeman/foreman-documentation/blob/6354c7b97978cff64d936985bdb7641b172e9fab/.github/workflows/deploy.yml#L314-L319

One possible approach would be to check out the `gh-pages` branch and then update as needed.

**Comment by Lennonka** [comment]
I misunderstood what you meant before.
How about a script at the end of the deploy that will do this for each guide: Read what images are used from GUIDE/index-*.html and delete everything that is not used under GUIDE/images/common. That shouldn't be that difficult.

**Comment by Lennonka** [comment]
We might want to wait with this for implementation of Antora #873 if it does deduplication natively. (As discussed with @ekohl)
