### ISSUE TITLE
Performance Tuning Guide not in navigation

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1277]
The new guide is still missing in the navigation.

Link: https://docs.theforeman.org/nightly/Performance_Tuning_Guide/index-foreman-el.html

**Comment by maximiliankolb** [comment]
FYI: Some files are only included in scenarios with Katello: https://docs.theforeman.org/nightly/Performance_Tuning_Guide/index-katello.html

**Comment by ekohl** [comment]
There are still quite a few issues with this guide. First of all, I opened https://github.com/theforeman/foreman-documentation/pull/1408 but that's just nightly.

Rendering also looks broken on https://docs.theforeman.org/nightly/Performance_Tuning_Guide/index-foreman-el.html#Configuring%20Puma%20Workers_performance-tuning

> FYI: Some files are only included in scenarios with Katello: https://docs.theforeman.org/nightly/Performance_Tuning_Guide/index-katello.html

Not enough: https://github.com/theforeman/foreman-documentation/pull/1410

**Comment by ekohl** [comment]
https://docs.theforeman.org/nightly/Performance_Tuning_Guide/index-foreman-el.html#Top_Performance_Considerations_performance-tuning still lists "Configure Hammer to reduce API timeouts" for which there are no instructions.

**Comment by ekohl** [comment]
We do link to https://docs.theforeman.org/nightly/Tuning_Performance/index-katello.html now, so I think can be considered done. I did notice that https://docs.theforeman.org/nightly/Performance_Tuning_Guide/index-foreman-el.html is an old guide we should have pruned.
