### ISSUE TITLE
Change letter casing to comply with the new GUI conventions

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#1295]
Based on discussion https://github.com/theforeman/foreman-documentation/pull/1290#discussion_r882913764 about Content Views, we should modify letter casing of some terms to make it consistent with UX changes.

However, we should consider unifying not just "content views", but also other terms, such as "repository", "product" and other.
Requires a more detailed analysis and discussion.
TBD for which Foreman version this is to be planned.

Then we can run a set of scripts to modify the docs, for example:
```
find guides/common/modules -type f | xargs sed -i "" "s/Content View/content view/g"
# note that -i handles differently on macOS; IMHO GNU sed does not require "" as parameter
# and potentially other combinations that you'd like to reword/change capitalization of.
```

**Comment by melcorr** [comment]
@maximiliankolb hope this is OK: https://community.theforeman.org/t/title-or-sentence-case-for-terms-in-foreman-katello/28837?u=mcorr 
Feel free to ask for more.

**Comment by Lennonka** [comment]
Adding a term for discussion: Host

**Comment by apinnick** [comment]
I think we can close this issue. The documentation has been updated so that it follows the sentence case guideline and there is a [UI issue](https://projects.theforeman.org/issues/37152) to change the interface to sentence case.

**Comment by maximiliankolb** [comment]
Makes sense to me.
