### ISSUE TITLE
Steps for upgrading a Smart Proxy are hidden behind katello,satellite ifdefs

### ISSUE THREAD

**Issue by adamruzicka** [theforeman/foreman-documentation#1388]
Doc in question https://github.com/theforeman/foreman-documentation/blame/master/guides/doc-Upgrading_and_Updating/topics/upgrading_capsule_server.adoc
The ifdef begins on L43 and ends at L88.

To be fair, the block does include some steps which are katello/satellite-specific, but in "vanilla Foreman" scenario, nothing tells you to update repositories, update packages and so on.

**Comment by maximiliankolb** [comment]
triage: valid issue; we need to find out which modules can be part of "upgrading Smart Proxy Server for foreman-el" and "upgrading foreman server/smart proxy server on Debian".

hint: check if procedures/concepts depend on katello, which automatically make them unsuitable for foreman-deb.
