### ISSUE TITLE
Improving typography - en dashes

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#1423]
I merged the PR #1358 the other day to give an example how typography can be improved in the docs.
Good typography makes the content look more professional and easier to read.

This focuses on dashes specifically, see also [How to use dashes](https://www.grammarly.com/blog/dash/).

Now we need to apply the new attributes where appropriate (in the following order of precedence):

- range: replace `\d - \d` with `\d{range}\d`
- en dash: replace `␣-␣` with `␣{endash}␣` where the symbol `␣` stands for a space

It's possible that there are further patterns where en dash would suit, but I need to analyze in greater depth.

**Comment by maximiliankolb** [comment]
I've already tried something like `find guides -type f -iname "*.adoc" | xargs sed -i "" "s/ - /{range}/g"`, but the task is actually a bit more complex.
