### ISSUE TITLE
Poll: Rename "Microsoft Azure Resource Manager" to "Microsoft Azure"?

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1456]
Hey!
I am currently working on bringing content on different compute resource providers upstream. See https://github.com/theforeman/foreman-documentation/pull/1455 (_draft_ as of 2022-08-15!).

I would like to **shorten** the name of the Azure CR to align with EC2 and GCE:

* Amazon EC2
* Google GCE
* Microsoft Azure

Is that acceptable for you? Do you have any other insight to why or why not to do this? I can accept a _no_ and would honestly avoid using an attribute for that.

A quick :+1: or :-1: on this issue counts as your vote. Thanks for everyone's input!

**Comment by ekohl** [comment]
I'm not sure on this. First of all, the plugin in question is https://github.com/theforeman/foreman_azure_rm and I'm pretty sure the gemspec description is used in the plugin overview in the UI. That's https://github.com/theforeman/foreman_azure_rm/blob/056f16eed081609cf1eace9fff20b5288f4634ea/foreman_azure_rm.gemspec#L10 (or `Azure Resource Manager as a compute resource for The Foreman` if you don't want to open it). I feel like those should be kept in sync, or it may be confusing for users.

**Comment by maximiliankolb** [comment]
It's actually named "Azure Resource Manager", but not the summary you've linked.

See my screenshots based on Foreman 3.3.0:
<img width="642" alt="Screenshot 2022-07-15 at 13 18 43" src="https://user-images.githubusercontent.com/12595287/179213432-71a38ee4-4e2f-448f-9af8-6e3acb6ec612.png">

![plugins_tab](https://user-images.githubusercontent.com/12595287/179214082-d10f58d9-864d-4931-a8a8-6d78ce576bf8.png)

**Comment by evgeni** [comment]
To add more confusion, the installer does name the plugin azure, not azure_rm:

https://github.com/theforeman/puppet-foreman/blob/master/manifests/plugin/azure.pp

**Comment by ekohl** [comment]
To be clear on my position: I think simply making it Microsoft Azure is probably fine, but I think things should be aligned (unlike the current situation).

**Comment by maximiliankolb** [comment]
Maybe "streamlining" the naming scheme is a bad idea. There is a second Foreman plugin for Google GCE on the horizon: https://github.com/theforeman/foreman_google

* `foreman-installer --enable-foreman-plugin-google`
* `foreman-installer --enable-foreman-compute-gce`

**Comment by chris1984** [comment]
Yeah seeing this, I vote we just keep it how it is.

**Comment by maximiliankolb** [comment]
Closing this; let's keep the existing chaos 🙃
