### ISSUE TITLE
Add multiple subnets docs

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#146]
We need to add this to install guides:

https://theforeman.org/plugins/katello/3.11/installation/index.html#multiple-subnets-and-domains

**Comment by maximiliankolb** [comment]
new link: https://theforeman.org/plugins/katello/nightly/installation/index.html

**Comment by adamlazik1** [comment]
I think it would be better if  https://github.com/theforeman/puppet-foreman_proxy/pull/705 before we start documenting this in order to avoid instructing users to edit config files directly.

**Comment by maximiliankolb** [comment]
triage: close due to lack of interest
