### ISSUE TITLE
Set RHEL attribute to "Enterprise Linux" for foreman-el and katello

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1478]
I propose two changes: "reword" the `RHEL` attribute to `EL` (cosmetic, invisible change) and for build targets "foreman-el" and "katello", set it to `Enterprise Linux`, which then resolves to "Enterprise Linux 7" and "Enterprise Linux 8". This is IMHO better than saying "CentOS 8" which is dead.

source: [comment in "Katello support for RHEL 8?"](https://community.theforeman.org/t/katello-support-for-rhel-8/28698/4?u=maximilian)

**Comment by ekohl** [comment]
That was my roughly intention with https://github.com/theforeman/foreman-documentation/pull/982. However, there I kept `RHEL` for when it really meant RHEL and changed `{RHEL}` to `{EL}` whenever it could. In Satellite `{EL}` expands to `{RHEL}`.

**Comment by ekohl** [comment]
Given #982 is now merged, I think we can consider this as resolved.
