### ISSUE TITLE
Compute Resource Prerequisites

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#15]
I am currently working on the Amazon EC2 topic and ran into something I don't know the answer to from a Foreman perspective.

I checked had Rahul done anything with this in the VMware file he was working on, and he had not dealt with it either. We will have to deal with this for every compute resource and every new compute resource that we add, so we need to figure it out. 

For example 

If you check the prerequisites:

 for https://github.com/theforeman/foreman-documentation/blob/aabd67903a49da47722be7ef4be7bd3523447441/guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc

It is similar to the https://github.com/theforeman/foreman-documentation/blob/aabd67903a49da47722be7ef4be7bd3523447441/guides/doc-Provisioning_Guide/topics/Cloud-Amazon_EC2.adoc that I'm working on.

Prerequisites for Amazon EC2 Provisioning

The requirements for Amazon EC2 provisioning include:

    Synchronized content repositories for Red Hat Enterprise Linux 7. For more information, see Synchronizing Red Hat Repositories in the Content Management Guide.

    A {SmartProxyServer} managing a network in your EC2 environment. Use a Virtual Private Cloud (VPC) to ensure a secure network between the hosts and the {SmartProxyServer}.

    An Amazon Machine Image (AMI) for image-based provisioning.

    An activation key for host registration. For more information, see Creating An Activation Key in the Content Management guide.

In Foreman, what replaces the content repos? Uploading an image? 
In Foreman for host registration, what do they do in place of activation keys? I can add an ifeval to say this is only available with Katello, but should I just have nothing for Foreman host registration there? 

Would appreciate any help.

**Comment by lzap** [comment]
> In Foreman, what replaces the content repos? Uploading an image?

In Foreman we have Installation Media resource which is essentially a table: name, URL where URL is parametrized so something like http://mirrors.centos.org/centos/$major/os/$arch which will give you some URL once you associate this with Architecture and Operating System (version = major.minor). That URL is then used to download everything, just like from Pulp in Satellite 6. So the only difference in Foreman is that you do not select Content Host / View / Source (there is no any) but you actually pick some Installation Media on the Host form instead. Katello basically "overrides" and Installation Media is unused completely (it's not blank we ship some entries there but users do not use it if they provision RH content). They can however still use IM to install let's say Debian or Ubuntu. That works fine (it's unsupported tho).



> In Foreman for host registration, what do they do in place of activation keys?

Nothing, you only need AKs when dealing with RHSM which is again only RH thing. In Fedora or CentOS there is no such thing - you simply install OS and it can consume all updates immediately. There is no registration step at all, it just works.

So all and all - we simply need to:

* hide RHSM / AK stuff from upstream or preferably keep it with some note this is only relevant when Katello plugin is installed and user deals with Red Hat content (some users do use Katello to install Red Hat related stuff)
* content synchronization should be again also with this note

So for this EC2 case I would write something like:

* Synchronized content repositories for Red Hat Enterprise Linux 7. For more information, see Synchronizing Red Hat Repositories in the Content Management Guide. (Note which shows up only for "foreman" build: This only applies when Katello plugin was installed).
* Installation media for other operating systems. (Note downstream only: Provisioning of OS other than Red Hat Enterprise Linux is not supported.)

**Comment by melcorr** [comment]
Perfect, thanks for the information.
