### ISSUE TITLE
Remove unnecessary comma

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#1508]
See https://github.com/theforeman/foreman-documentation/pull/982#discussion_r934334869

**Comment by ekohl** [comment]
@maximiliankolb is this still something you want to do or should we close it?

**Comment by adamlazik1** [comment]
Created PR.

**Comment by maximiliankolb** [comment]
Thanks Adam. Closing this issue.

**Comment by ekohl** [comment]
@maximiliankolb I linked the PR so this issue would automatically be closed when it's merged. You can see it on the right side in the Development block.
