### ISSUE TITLE
Should the note about deleting/removing CV be there?

### ISSUE THREAD

**Issue by Levi-Leah** [theforeman/foreman-documentation#1635]
file: guides/common/modules/proc_creating-a-content-view.adoc

```
+
[NOTE]
*Remove* and *Delete* are similar but the *Delete* option deletes an entire Content View and the versions associated with that lifecycle environment.
The *Remove* option allows you to choose which version you want removed from the lifecycle environment.
```

Additional info: https://github.com/theforeman/foreman-documentation/pull/1634/files/37f249bc6bdff0065244b4e377507550d7411634#r972662116

**Comment by asteflova** [comment]
For `TW uni course` students: Estimated effort -- M.

**Comment by xzimmerm** [comment]
Hi, i'd like to sign up for this issue.

**Comment by asteflova** [comment]
@xzimmerm Your PR has been merged so you can now close this issue. (It won't happen automatically in this case because you opened the new, related https://github.com/theforeman/foreman-documentation/issues/3001.)
