### ISSUE TITLE
/vendor directory missing in .gitignore on some branches

### ISSUE THREAD

**Issue by adamlazik1** [theforeman/foreman-documentation#1658]
I have noticed that while the `/vendor` directory is included in the `.gitignore` file on master and on the  3.3 branch, it is missing from the file on 3.2, 3.1, 2.5, and possibly other branches (I have not checked all). This is problematic when creating PR against the specific branch and using `git add .` to add changed files to the staging area, because it adds unwanted files included in the `/vendor` directory. What is the right way to fix this? Do I create a separate PR against each branch?

**Comment by ekohl** [comment]
> What is the right way to fix this? Do I create a separate PR against each branch?

Yes, you do exactly that.

**Comment by adamlazik1** [comment]
Alright, thanks!
