### ISSUE TITLE
Describe new dynflow scaling (2.1)

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#173]
https://github.com/theforeman/theforeman.org/pull/1592

**Comment by maximiliankolb** [comment]
@Imaanpreet Do you think the performance tuning guide missing something?

**Comment by Imaanpreet** [comment]
> @Imaanpreet Do you think the performance tuning guide missing something?

Hello @maximiliankolb : we are going to test dynflow perf & scale testing in the next release. After doing the scale testing, I will be in a good shape to suggest something here. Right now, what ever Adam suggested looks good to me. Thank you.

**Comment by maximiliankolb** [comment]
Done with https://docs.theforeman.org/nightly/Tuning_Performance/index-katello.html#Dynflow_Tuning_performance-tuning
