### ISSUE TITLE
Update proc_installing-the-discovery-service.adoc

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#1766]
For Satellite/Orcharhino it tells uses to install `tfm-rubygem-smart_proxy_discovery` but that should be `rubygem-smart_proxy_discovery` on EL8. That also needs to be backported to stable releases.

Then for upstream it downloads http://downloads.theforeman.org/discovery/releases/3.5/ but that's not the latest release. In fact, there is a `/latest` there and that's the default so I wonder if we should drop the parameter altogether.

Additionally, the service restart and proxy refreshing is only needed when the installer isn't used, AKA the Satellite/Orcharhino instructions. Ideally a feature is implemented in the installer so users have a smooth installation, but for now this is where we are.

**Comment by evgeni** [comment]
@ekohl I think that can now be closed?
