### ISSUE TITLE
RFE: dnf needs restarting -r for el8 in guides/doc-Upgrading_and_Updating/topics/snip_needs_reboot.adoc

### ISSUE THREAD

**Issue by pcfe** [theforeman/foreman-documentation#1858]
Since Foreman on EL is EL8 these days (no more EL7), it would be nice if guides/doc-Upgrading_and_Updating/topics/snip_needs_reboot.adoc recommended `dnf needs-restarting -r` instead of `rpm --query --last kernel | head -n 1 && uname -r`

something along the lines of:

```
[...]
ifndef::foreman-deb[]
.. Check if a reboot is needed:
+
[options="nowrap"]
----
# dnf needs-restarting --reboothint
----
. Optional: If the previous command told you to reboot, then reboot the system:
endif::[]
+
[options="nowrap"]
----
# reboot
----
```

#### example of no reboot needed:

```
[root@foreman ~]# dnf needs-restarting --reboothint
No core libraries or services have been updated since boot-up.
Reboot should not be necessary.
```

#### example of reboot needed:

```
[root@foreman ~]# dnf needs-restarting --reboothint
Core libraries or services have been updated since boot-up:
  * kernel

Reboot is required to fully utilize these updates.
More information: https://access.redhat.com/solutions/27943
```

#### availability of the command

with (AFAIR the recommended install set)
```
%packages
@Base
```

this command is available.

**Comment by ekohl** [comment]
And today I learned something new. Thanks, this is much easier. Could you come up with a pull request for this?
