### ISSUE TITLE
Avoid /etc/foreman-installer/scenarios.d

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#190]
This directory will be moved in the future (probably `/var/lib/foreman-installer`) to signify the user is not supposed to modify these files. The way I look at it is that it's similar to suggesting open a database console and `SELECT * FROM settings` rather than going to the settings page.

Would it be better to suggest `foreman-installer --full-help` and let users look at `(default: $VALUE)` instead? The benefit is that it's not scenario specific and always the same command. Note that `--scenario $scenario` only needs to be passed on the first installation. After that a scenario has been selected and will always be used.

**Comment by maximiliankolb** [comment]
somewhat related: https://projects.theforeman.org/issues/36957

**Comment by maximiliankolb** [comment]
triage: let's do this soon.
