### ISSUE TITLE
Fix all links

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#20]
We have several types of links:

* `link:/html/content_management_guide/importing_red_hat_content#Importing_Red_Hat_Content-Synchronizing_Red_Hat_Repositories[Synchronizing Red Hat Repositories]` (converted by upstreamize)
* `https://access.redhat.com/documentation/en-us/red_hat_satellite/6.4/html/installing_satellite_server_from_a_connected_network/preparing_your_environment_for_installation#ports_prerequisites[Port and Firewall Requirements]`

We should convert all links that link content across guides to something like:

```
{base_url}/html/installing_satellite_server_from_a_connected_network/preparing_your_environment_for_installation#ports_prerequisites[Port and Firewall Requirements]
```

Where base_url is a variable:

```
:base_url: https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}
```

It will be different for foreman and satellite of course.

External links to RHEL (and other) docs are correct: `https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Getting_Started_Guide/index.html[Red Hat Enterprise Linux 7 Virtualization Getting Started Guide]` and they should be kept as-is.

**Comment by melcorr** [comment]
Shall we close this issue now @lzap  ? As part of PR #51
