### ISSUE TITLE
Duplicate procedures for creating a PAT?

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#2073]
Hi all,

While reviewing Adam's PRs (https://github.com/theforeman/foreman-documentation/pull/2050 & https://github.com/theforeman/foreman-documentation/pull/2066) this week I had a feeling that I've seen/written something similar before but didn't act on it. Today, I found https://docs.theforeman.org/nightly/Administering_Project/index-katello.html#Creating_an_API_Only_User_admin.

Do you think we should/can consolidate this in some shape or form?

cc @adamlazik1

**Comment by adamlazik1** [comment]
Thanks for noticing this! Although, this procedure is slightly different as it talks about creating an API-only user and it's main subject is actually not to discuss Personal Access Tokens feature. So I think is probably okay to leave procedures in both places? That being said, I think this procedure could use some love, so I will make a PR  where I delete the creating PAT part and just link the other procedure instead.
