### ISSUE TITLE
Splitting "Managing Hosts" - Let's separate OpenSCAP

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#2171]
Hi! I've been working on the chapter about **managing security compliance** of hosts (a.k.a. OpenSCAP), which was originally in the _Admin_ guide. I've planned to move it to _Managing Hosts_, however, that guide is already quite lenghty and I'm not happy with this solution.
We've been discussing previously that we should reduce the number of chapters in _Managing Hosts_ and I think that OpenSCAP is a great opportunity to not make it longer. :smile: 

- My suggestion: Let's make the security compliance chapter into a standalone guide.
- Proposed title: **Managing Security Compliance _of_ Hosts** (A) or **Managing Security Compliance _on_ Hosts** (B)
- Number of chapters: 8+, i.e. long enough to make a separate title
- PROs: Reduces the length of _Managing Hosts_. It will also make the navigation nicer for the lower level of headings in Foreman docs

Opinions? Or you can just give me a :+1: if you agree. :)

**Comment by Lennonka** [comment]
@adamlazik1 @maximiliankolb @ekohl

**Comment by Lennonka** [comment]
Support from the Satellite TW lead off GH.

**Comment by adamlazik1** [comment]
I personally would not do this; however; if it has support from above and if you see sense in doing it (and you are undoubtedly familiarized with the chapter much more than me, so I don't really have much place to talk :sweat_smile:), then it is probably a good idea to do it. As for the title, I lean more towards **Managing Security Compliance _on_ Hosts**

**Comment by ekohl** [comment]
I think it makes sense to split up the too long admin & managing hosts guides.

**Comment by maximiliankolb** [comment]
Yes, +1 from me for splitting guides into smaller secions. Can we go with "Managing Security Compliance"? We also have "Managing Content" which does not include "of/on hosts"?

Either way: thanks for proposing this & taking charge!

**Comment by Lennonka** [comment]
At first, I've kept "Managing Security Compliance on Hosts" for the Satellite build, but on second thought, I think that Max's suggestion is better.
