### ISSUE TITLE
[URGENT] GH Pages not found?

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#2238]
https://theforeman.github.io/ reports 404 Not Found and it's [breaking our builds](https://github.com/theforeman/foreman-documentation/actions/runs/5282645219/jobs/9557829155?pr=2237).
What happened? How do we fix this?

**Comment by Lennonka** [comment]
@ekohl Please, we need help here :))

**Comment by ekohl** [comment]
We deleted those because they were outdated, see https://community.theforeman.org/t/rfc-removing-storybook/33644 for more information. #2242 fixes the links.
