### ISSUE TITLE
Improving WebUI navigation with headings

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#2268]
Currently, we use navigation such as:

**Hosts** > **Policies**

However, the list of list items in the navigation is quite long and for new users it would be useful to include the heading under which this item resides. For example:

**Hosts** > [Compliance] **Policies**

We can discuss the ideal syntax here and then create a PR to fix it everywhere at once.

This conversation started in https://github.com/theforeman/foreman-documentation/pull/2261#pullrequestreview-1500171906

**Comment by Lennonka** [comment]
cc @asteflova

**Comment by adamlazik1** [comment]
My personal view is to not implement this change as I still think it can be confusing to a new user who might look for **[Compliance] Policies** explicitly. However; if there are more people who think that this is a good idea then I won't object.

**Comment by asteflova** [comment]
I like the idea of including "Compliance" and equivalent labels to the docs. When describing a clickable path to a GUI option, it makes sense to include the whole path including all the labels leading up to the final button.

I don't like *Hosts* > [Compliance] *Policies*, but can't really explain why. Probably personal or aesthetic preferences :) I guess it also adds complexity -- it looks unusual so it makes me (as a user) think too much ("Why does the middle bit look different? Why is it in brackets?").

My preference would be *Hosts* > *Compliance* > *Policies* >. To me, the path to the final element consists of all three (even though Compliance is not "clickable").

Has anyone checked the IBM style guide?

I'm going to check AsciiDoc syntax reference to see if it has some guidance on this. I know good ol' DocBook had markup for GUI paths, so I might find something useful for AsciiDoc too.

**Comment by asteflova** [comment]
> I'm going to check AsciiDoc syntax reference to see if it has some guidance on this. I know good ol' DocBook had markup for GUI paths, so I might find something useful for AsciiDoc too.

I found this: https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/  Based on this, I believe the correct way to mark Lena's example up would be:

`menu:Hosts[Compliance > Policies]`

I haven't tested it, though, so I don't know if the tooling chain would accept it.

Generally speaking, using markup like this would free us from having to think about how to format the GUI path ourselves, which I think is the purpose of using a markup language in the first place.

Anyway, all of this is just my 2 cents, I'd be happy to learn why I'm wrong :)

**Comment by Lennonka** [comment]
> I found this: https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/ Based on this, I believe the correct way to mark Lena's example up would be:
> 
> `menu:Hosts[Compliance > Policies]`

This looks cool! I'm gonna test it and report back.

**Comment by maximiliankolb** [comment]
FYI: Tested in Antora using `:experimental:`: https://docs.antora.org/antora/latest/asciidoc/ui-macros/#set-the-experimental-attribute

Looks good to me; however, it does not really fix the issue that some plugins in Foreman have unclickable headings in the navigation; and some of their clickable subheadings only really make sense when you know the context; i.e. the name of the plugin or its functionality.

I am totally OK using `menu:`, `kbd:`, and `btn:`.

**Comment by ekohl** [comment]
FYI: navigation UX is going to change in Foreman 3.8. https://community.theforeman.org/t/rfc-navigation-once-again/33065 has the details. The menu items themselves shouldn't change.

**Comment by asteflova** [comment]
I think that with the new UI search function, changing the way we documenting web UI navigation paths is no longer necessary. When searching for a particular menu item, users can now search for it rather than hunt it down manually. @Lennonka What do you say, do you want to keep the issue open or can we close it?

**Comment by Lennonka** [comment]
Yeah, the problem has resolved itself, so I'm closing it :)
