### ISSUE TITLE
Extract provisioning prerequisites

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#23]
These bullets are very often same (installation media, activation keys), maybe it is worth extracting them into a separate adoc file and including it everywhere.

**Comment by rahulbajaj0509** [comment]
By everywhere, do you mean at the start of all the chapters? Sorry, not sure, can you explain?

**Comment by lzap** [comment]
I mean those bullet points do appear a bit same, thus I opened this ticket to investigate more.

**Comment by melcorr** [comment]
I think sometimes there can be slight differences, but I have no problem looking into this and seeing is it worth it. I think that they are copied/pasted after verifying that each new compute resource needs each thing.
