### ISSUE TITLE
Installation guides state Puppet 5 is the minimum version

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#2333]
We have raised the minimum version a while back. Each branch should be considered because we raised it to 6.15 and later to 7.

**Comment by maximiliankolb** [comment]
We mention "Puppet" quite a lot throughout the docs, for example in

* guides/common/modules/proc_configuring-repositories-el.adoc
* guides/common/modules/proc_configuring-repositories-deb.adoc
* guides/common/modules/proc_enabling-puppet.adoc
* guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
* guides/common/modules/ref_performing-configuration-management.adoc
* guides/common/modules/con_how-puppet-integrates-with-project.adoc
* guides/doc-Planning_for_Project/topics/Configuration_Management_Support.adoc

Files with obvious version numbers:

```
$ rg -i "puppet [0-9]"
guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-registration.adoc
43:* Add a host parameter named `enable-official-puppet7-repo` for the Puppet 7 release repository.

guides/common/modules/proc_installing-and-configuring-puppet-agent-during-host-provisioning.adoc
54:* Add a host parameter named `enable-official-puppet7-repo` for the Puppet 7 release repository.

guides/common/modules/ref_supported-puppet-versions-and-system-requirements.adoc
9:* Puppet 7
13:For more information, see https://puppet.com/docs/puppet/7/system_requirements.html[System Requirements for Puppet 7] in the _Open Source Puppet_ documentation.
```

* Puppet version for foreman-installer to install Foreman/Katello: https://github.com/theforeman/foreman-installer/blob/develop/spec/puppet_version_spec.rb#L4
* Puppet version for foreman_puppet to configure managed hosts: is it the same?

**Comment by ekohl** [comment]
> Puppet version for foreman-installer to install Foreman/Katello: https://github.com/theforeman/foreman-installer/blob/develop/spec/puppet_version_spec.rb#L4

We also reflect this in the foreman-installer packages themselves. So it shouldn't be possible to install the installer with a too old Puppet version.

> Puppet version for foreman_puppet to configure managed hosts: is it the same?

I just answered this yesterday: https://github.com/theforeman/foreman_puppet/issues/371#issuecomment-1764313783

The short summary is that our installer is stricter in what it supports than the other parts.

Though the third part is compatibility in the provisioning of new hosts.

**Comment by maximiliankolb** [comment]
relates to

https://github.com/theforeman/theforeman.org/pull/2103
https://github.com/theforeman/theforeman.org/pull/2107
https://github.com/theforeman/theforeman.org/pull/2108

since 3.4: you need puppet 6
since 3.7: you need puppet 7

your Puppet modules to configure managed hosts need to be compatible with that version!
