### ISSUE TITLE
Add users to TheForeman GH organization

### ISSUE THREAD

**Issue by Lennonka** [theforeman/foreman-documentation#2377]
Please, add the following users with limited permissions: @AkshayGadhaveRH @asteflova @bangelic @mjivraja @mdolezelova

**Comment by ekohl** [comment]
Invitations were sent out.

**Comment by igkioka** [comment]
@ekohl, all the writers seem to have merge rights. Is this expected? As of now only Adam and Lena should have.

**Comment by ekohl** [comment]
> @ekohl, all the writers seem to have merge rights. Is this expected? As of now only Adam and Lena should have.

That was what I specified because I wanted to give them some permissions on the repo so you could assign them. However, I can maybe split up the group in @theforeman/documentation which only has basic permissions and one that has write access.

Should I try that?

**Comment by ekohl** [comment]
I've now created @theforeman/documentation and @theforeman/documentation-write which I think should achieve this. Please check.

**Comment by Lennonka** [comment]
Verified that I can add above-mentioned users as Reviewers in PRs.
