### ISSUE TITLE
Duplication in listing individual loggers

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#2403]
Documentation currently provides a list of individual loggers that can be enabled for selective debugging. However, that list is not complete. Rather than keeping the list up-to-date on the documentation side, I'd like to improve the list of loggers on the Foreman project side:

https://github.com/theforeman/foreman/blob/55b0a9f1b1b2871976c5ea7b7874f18afcf1a8ab/config/application.rb#L279-L294:

If the list in application.rb is improved with comments on how to interpret the list and on the function of the loggers, the documentation could then direct users to that file rather than maintain a duplicate list of loggers.

I'm filing this issue to track my progress on:
1. Getting application.rb updated
2. Subsequently updating the documentation

**Comment by maximiliankolb** [comment]
triage: guides/common/modules/ref_overview-of-individual-loggers.adoc is there, so we already have a cross-reference. -> close for now.
