### ISSUE TITLE
Duplication in snip_steps-needs-reboot.adoc

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#2424]
Since ec4aea364e2d551d07f2f507cf8a4ce735ccc4a9 there's `guides/common/modules/snip_steps-needs-reboot.adoc` which is almost a copy of `guides/doc-Upgrading_Project/topics/snip_steps-needs-reboot.adoc` except that it lists the actual reboot as optional. I think it's optional in both cases so we can unify on a common snippet.

**Comment by mjivraja** [comment]
@AkshayGadhaveRH are you planning to shift from `topics` to `common/modules` anytime soon? If yes, it should address this issue.

**Comment by AkshayGadhaveRH** [comment]
> @AkshayGadhaveRH are you planning to shift from `topics` to `common/modules` anytime soon? If yes, it should address this issue.

@mjivraja yep I am planning on doing that in the next few days.

**Comment by maximiliankolb** [comment]
triage: duplicate files are no longer present. -> close.
