### ISSUE TITLE
Replace apt-get with apt in Foreman-deb

### ISSUE THREAD

**Issue by mjivraja** [theforeman/foreman-documentation#2467]
`apt` is a subset of `apt-get` and `apt-cache` that provides necessary commands for package management. Moreover, it is an enhanced approach to apt-get that eliminates the use of further options/arguments. So with apt, you get all the necessary tools in one place.

In my case, if I want to upgrade the Linux kernel with simply `apt-get upgrade` I can't. But with `apt upgrade` I can. Hence, I believe that as `apt` is the advanced and recommended approach for Debian, we can replace the package manager apt-get for `foreman-deb` with apt. I am not sure, if `apt-get upgrade` can upgrade or update the Foreman-deb without any extra options/arguments.

Note: apt-get is not deprecated at all and there is no news on it.

**Comment by ekohl** [comment]
> In my case, if I want to upgrade the Linux kernel with simply `apt-get upgrade` I can't.

Could you elaborate on this? It's been a while since I used `apt-get`, but I thought there was no difference compared to `apt` here.

**Comment by mjivraja** [comment]
In `apt-get --simulate upgrade`, I saw that the packages of the Linux kernel were kept back. I need to go through `apt-get dist-upgrade` path to update those.

**Comment by ekohl** [comment]
Ah right. https://itsfoss.com/apt-get-upgrade-vs-dist-upgrade/ does clarify it well. :+1: for using `apt`.

**Comment by mjivraja** [comment]
Closing this issue as PR for the same has been considered.
