### ISSUE TITLE
Update Keycloak Authentication docs

### ISSUE THREAD

**Issue by lumarel** [theforeman/foreman-documentation#2499]
As mentioned in [Discourse](https://docs.theforeman.org/nightly/Installing_Server/index-katello.html#Configuring_Project_with_Keycloak_Authentication_keycloak-general) it would be needed to update the Keycloak documentation, as since a major versions not only the UI changed, but also the API was moved to another place.

Would take the time to rewrite this, if no one is already working on it.

**Comment by maximiliankolb** [comment]
relates to https://community.theforeman.org/t/sso-with-azure-ad-in-foreman-3-7/35075

**Comment by lumarel** [comment]
Oh thanks, looks like I copied the wrong link 👍🏻

**Comment by maximiliankolb** [comment]
I've also added this topic to our (open) docs triage meeting on thursday: https://community.theforeman.org/t/documentation-team-meeting-2023-10-19/35446
