### ISSUE TITLE
Convert all "Content View" occurrences to lower case

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#2553]
The documentation currently uses both the capitalized and lower-case variants of "C/content V/view". In the web UI, the form for creating content views uses lower-case only.

It seems like a good idea to convert all occurrences to lower case.

**Comment by adamlazik1** [comment]
I completely agree. To me it doesn't make much sense to have it capitalized since it is not a product name.

**Comment by Lennonka** [comment]
+1

**Comment by asteflova** [comment]
Duplicate of https://github.com/theforeman/foreman-documentation/issues/2747

**Comment by maximiliankolb** [comment]
> Except for titles, of course.

Even for titles.

**Comment by maximiliankolb** [comment]
change to sentence case.

**Comment by apinnick** [comment]
I created a [Foreman issue](https://projects.theforeman.org/issues/37152), for inconsistent capitalization in UI, that might help in the future.

**Comment by Lennonka** [comment]
@mjivraja FYI ^^
