### ISSUE TITLE
Configure branch protection on stable branches

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#2646]
> We should configure the project to not allow force pushes to "X.Y" & "master" branches.

_Originally posted by @maximiliankolb in https://github.com/theforeman/foreman-documentation/issues/2644#issuecomment-1864628904_

I've created an empty rule for branches matching `*.*` which should prevent force pushes.

The question is, how far do we want to go with this? We can also mandate a PR, but that prevents cherry picks as we do them today.

**Comment by maximiliankolb** [comment]
Thanks for creating this rule.

I think preventing force pushes on stable branches is the perfect balance; preventing cherry-picks would really impact my workflow.

IMHO we can close this issue with "done" but lets hear other options too.

**Comment by ekohl** [comment]
I'll note I didn't test this because of the risk. I'd like to keep it open and discuss this during the next docs meeting.

**Comment by adamlazik1** [comment]
I also think preventing force pushes and allowing regular pushes is a good balance.
