### ISSUE TITLE
Remove performance tuning guide from Foreman-el

### ISSUE THREAD

**Issue by mjivraja** [theforeman/foreman-documentation#2687]
While working on the performing tuning guide, I came to know from @ekohl 's [comment](https://github.com/theforeman/foreman-documentation/pull/2666#issuecomment-1900588809) that `Tuning Project Server with Predefined Profiles` was never a part of `foreman-el`. 

However, it is still the part of `foreman-el` until version 3.5 - https://docs.theforeman.org/3.5/Installing_Server/index-foreman-el.html#tuning-with-predefined-profiles_foreman

Should this be fixed?

**Comment by ekohl** [comment]
3.5 is not supported anymore and I don't think we link to it so I wouldn't spend too much effort on it

**Comment by mjivraja** [comment]
Thank you.
Closing this issue.
