### ISSUE TITLE
Update on NIST reference number 140-2 in FIPS Complaint Hosts

### ISSUE THREAD

**Issue by mjivraja** [theforeman/foreman-documentation#2725]
While going through #2723 I discovered that https://csrc.nist.gov/pubs/fips/140-2/upd2/final was throwing `503`. However, it worked after trying 2-3 times. I read in the publications that `Testing of cryptographic modules against FIPS 140-2 will end on September 22, 2021`. 

Also, they shared the new publication of `140-3`. I found - https://csrc.nist.gov/pubs/fips/140-3/final later on. 

Does this have an impact on documentation?

**Comment by maximiliankolb** [comment]
triage: could not reproduce.
