### ISSUE TITLE
List of capitalized nouns for Contributing guidelines

### ISSUE THREAD

**Issue by apinnick** [theforeman/foreman-documentation#2744]
Add a "Capitalization" section to [Contributing](https://github.com/theforeman/foreman-documentation/blob/master/CONTRIBUTING.md) so that new contributors know what needs to be capitalized. To make it easy to maintain, I recommend creating a single list in alphabetical order. If it gets too long, we can consider using generic terms like "Software packages" if we end up with too many examples to list.

Suggestions:
Ansible, Salt, Chef, Python, Kickstart, Discovery (service), Tracer (utility), Insights (RH product), OpenScap, Hammer, Candlepin, Pulp, Redis, Puppet

**Comment by maximiliankolb** [comment]
Additions: Content View, Library, Red Hat Network, PostgreSQL, Salt Minions,

Not capitalied: Red Hat subscription manifests, subscriptions, manifest

**Comment by adamlazik1** [comment]
Speaking of, I wonder if "Content View" should be capitalized after all. AFAIK it is not a product name.

**Comment by apinnick** [comment]
> Speaking of, I wonder if "Content View" should be capitalized after all. AFAIK it is not a product name.

I was wondering that myself. There is a separate Foreman issue to lower-case this term. We might have to create a lot of PRs to fix capitalization.
