### ISSUE TITLE
Switch "Content View" to lowercase again?

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#2747]
With 65719dc10961cfb42a21e25456df3ae5c90efbb4 (PR #1050), we have changed "content view" to "Content View". Now we're discussing if we want to revert this after we have changed all headings to sentence case.

If we decide to do this, we have to remove it from the list of capitalized words.
I think it would be a fairly simple `find | xargs sed` command but still needs review etc.

**Comment by adamlazik1** [comment]
I actually tried it before, and it is not that simple. You have to account for "Content view" at the beginning of a sentence/title (not that difficult), "Content View" in navigation (also not that difficult cause it should always be in bold) and for instances of CV inside tables, where capitalization may vary - sometimes all of the items use sentence case.

In summary: yes, the `sed` command will do most of the work but manual edits after will be required.

**Comment by maximiliankolb** [comment]
Closed in favor of https://github.com/theforeman/foreman-documentation/issues/2553
