### ISSUE TITLE
Depends on build target

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#2770]
Depends on build target

_Originally posted by @maximiliankolb in https://github.com/theforeman/foreman-documentation/pull/2607#discussion_r1420478127_

**Comment by asteflova** [comment]
Hi @maximiliankolb, in https://github.com/theforeman/foreman-documentation/pull/2607#discussion_r1420478127, you wrote that you'd specify build targets for orcharhino. Is this still on your to-do list? If so, would you consider assigning this issue to yourself?

**Comment by maximiliankolb** [comment]
@asteflova Yes, thanks.

**Comment by maximiliankolb** [comment]
Fixed on "master"; `guides/common/modules/con_content-flow-in-project.adoc` LGTM.

image will be unbranded as soon as I incorporate "Planning for Foreman" in downstream docs.
