### ISSUE TITLE
Planning for {Project} Guide - Content Sources terminology

### ISSUE THREAD

**Issue by jeremylenz** [theforeman/foreman-documentation#2794]
The "Content Sources" section of the guide talks about the various places from which Katello content can come. I think this should probably be renamed "Sources of content," since we already have two other (unrelated) things that we refer to as content sources:

* Change Content Source - In this context, a "content source" is the Smart Proxy from which a host gets its content. The smart proxy's url is configured in the [server] section of its `rhsm.conf` subscription-manager configuration. To change the Smart Proxy from which a host gets content, you can use the Change Content Source feature and it will perform both the server-side and client-side steps. This is documented here -> https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#Changing_the_Content_Source_of_a_Host_managing-hosts
* Alternate Content Sources - This is a way to redefine the primary location from which Katello syncs content for the repositories under a given product. This is documented here -> https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Managing_Alternate_Content_Sources_content-management

**Comment by asteflova** [comment]
The section is now named "Sources of content": https://docs.theforeman.org/nightly/Planning_for_Project/index-katello.html#content-sources-in-Foreman_planning
