### ISSUE TITLE
Check if "Content Host" needs to be removed from Prereqs too

### ISSUE THREAD

**Issue by asteflova** [theforeman/foreman-documentation#2889]
A follow-up on https://github.com/theforeman/foreman-documentation/pull/2569 and https://github.com/theforeman/foreman-documentation/pull/2888.

We removed mentions of "Content Hosts" from a section title and introduction, as requested in https://bugzilla.redhat.com/show_bug.cgi?id=2209380.  However, "Content Host" is mentioned in Prerequisites as well: https://theforeman-foreman-documentation-preview-pr-2888.surge.sh/3.5/Upgrading_and_Updating/index-satellite.html#updating_satellite

Let's check in newer docs whether we should remove it as well.

_Originally posted by @Lennonka in https://github.com/theforeman/foreman-documentation/issues/2888#issuecomment-1998215778_

**Comment by asteflova** [comment]
For `TW uni course` students: Estimated effort -- S.

**Comment by xzimmerm** [comment]
Hi, i'd like to sign up for this issue.

**Comment by xzimmerm** [comment]
I am not really sure what newer docs mean, but i have scoured https://docs.theforeman.org/.

I have found mentions of Content Host in Prerequisites from version [3.6](https://docs.theforeman.org/3.6/Upgrading_and_Updating/index-satellite.html#updating_satellite) to [3.1](https://docs.theforeman.org/3.1/Upgrading_and_Updating/index-satellite.html#updating_satellite).
In versions  [3.4](https://docs.theforeman.org/3.4/Upgrading_and_Updating/index-satellite.html#updating_satellite), and 3.6 Content Host is still mentioned in the section title. 
From version 3.7 i could not find the page (maybe it has a different route?). There were mentions of Content Host in all versions older than 3.1, but some of them still had the updating Content Hosts section in them.

Again, I am not really sure if this is what i was supposed to check so if not please point me in the right direction.

**Comment by asteflova** [comment]
Thanks for the investigation! You're right. To summarize:

* For versions 3.6-3.1, "Content Hosts" is mentioned in the Prerequisites section.
* For versions 3.6 and 3.4, "Content Hosts" is also mentioned in chapter heading and chapter introduction.

(This is wrong because the chapter includes these sections: `Updating Satellite Server`, `Updating Disconnected Satellite Server`, `Updating Capsule Server`. There is no section on content hosts anymore.)

You will need 2 PRs to address these issues:

1. PR against branch 3.6, to remove "Content Hosts" from Prerequisites.
2. PR against branch 3.6, to remove "Content Hosts" from chapter heading and introduction.

*When you create the topic branches, don't create them from `master`.* First check out branch `3.6` (`git checkout 3.6`), and then create your branch.

**Comment by xzimmerm** [comment]
Thank you for the help, the PRs are opened i hope i've done it right.

**Comment by asteflova** [comment]
@xzimmerm PRs have been merged, please close this issue.

**Comment by xzimmerm** [comment]
I can't see the "Close issue" button, so i am pretty sure i don't have the permissions for that.
