### ISSUE TITLE
Add header or link to homepage

### ISSUE THREAD

**Issue by lamek** [theforeman/foreman-documentation#294]
I think a small but impactful improvement would be a way for the viewer to navigate easily back to the homepage. Right now when viewing a guide there's no visual place you can click to get home.
![image](https://user-images.githubusercontent.com/3738757/97377295-1320a680-1896-11eb-873d-fa32e043d1f4.png)

Some ideas:
* add "Home" above the toc and link to the home page
* add Foreman logo above toc and link to the home page

**Comment by lamek** [comment]
I would love to try suggesting some code to help with this but I can't find where "Table of Contents" is generated from. I tried searching the repo for "Table of Contents" and a few ids and classes, but no luck.

Any help is appreciated.

**Comment by lzap** [comment]
Hello, thanks for report. We are in process of moving to this new documentation, one of the next items to solve is some template that will add required button or picture. For now, use back button, it's on our radar.

**Comment by melcorr** [comment]
@laviro - do you think that the UX folks might be able to help us with this item as we move towards Foreman 3.0 and make these docs official!

**Comment by laviro** [comment]
@melcorr I am pretty sure we can help!
Let's add it to the next UX meeting agenda: https://community.theforeman.org/t/ux-interest-group-meeting-09-08-21/24703?u=laviro

**Comment by melcorr** [comment]
Thank you @laviro ! Added.

**Comment by ekohl** [comment]
> I would love to try suggesting some code to help with this but I can't find where "Table of Contents" is generated from. I tried searching the repo for "Table of Contents" and a few ids and classes, but no luck.

It is generated by asciidoctor. https://docs.asciidoctor.org/asciidoctor/latest/ is the documentation for it. It look like you can pass `--template-dir` (requires the `tilt` gem to be installed). However, I struggle to find which file to drop in. https://github.com/asciidoctor/asciidoctor/tree/master/test/fixtures has various filenames, but I don't know if that's exactly the ones.

https://github.com/darshandsoni/asciidoctor-skins is really only CSS, not templates so that doesn't help either.

**Comment by lzap** [comment]
We already use "head" to put the "Nightly" banner. It is here:

https://github.com/theforeman/foreman-documentation/blob/master/guides/common/docinfo.html

then used in the Makefile

https://github.com/theforeman/foreman-documentation/blob/master/guides/common/Makefile#L56

Maybe just bunch of HTML could do it. There is also a "header" and "footer" feature. All you need to do is to create `docinfo-header.html` and `docinfo-footer.html` files and put HTML it. Then call `make` to build it.

**Comment by melcorr** [comment]
Think that this work is complete as described by the reporter.
