### ISSUE TITLE
Idea: Document how to mirror Ubuntu Pro packages?

### ISSUE THREAD

**Issue by stdevel** [theforeman/foreman-documentation#2987]
Hi community,
I recently stumbled upon a request where synchronizing Ubuntu Pro packages was required. I had a look at the service and figured out how to mirror these packages: https://cstan.io/en/post/2024/04/ubuntu-pro-mirror/

**TL;DR**: You will need to extract a bearer token and GPG key while the repository URLs are well-known. Putting this together results in the possibility to mirror these packages.

Would you be interested in a PR that adds these information to the Katello documentation? I'm asking because I don't know whether you want to see these information in the documentation as they can be used to misuse the Ubuntu Pro offering. On the other hand, this can also happen when mirroring RHEL or SLES packages.

Let me know, what you think - happy to help with a PR.

**Comment by maximiliankolb** [comment]
Hey Christian, we already have orcharhino docs on how to synchronize Ubuntu ESM repositories: https://docs.orcharhino.com/or/docs/sources/guides/ubuntu/managing_content/importing_content.html#Synchronizing_Ubuntu_Extended_Life_Support_Content Do you have something similar in mind for Ubuntu Pro?

**Comment by stdevel** [comment]
That looks exactly like the documentation I was going to write. Had only a look at the Katello documentation, but not at the Orcharhino pages. Ubuntu Pro basically consists of ESM packages and some additional offers (e.g. Kernel Live Patching, FIPS and USG).

Do you want to share these instructions with the Foreman documentation? Would be great to also have them in the upstream documentation.

**Comment by maximiliankolb** [comment]
Yes, I can create an upstream PR within the next two weeks.

**Comment by stdevel** [comment]
Ohai @maximiliankolb, I hope you're fine - do you have any update for us? :)

**Comment by maximiliankolb** [comment]
Hey @stdevel 

I finally got around to creating a PR: https://github.com/theforeman/foreman-documentation/pull/3075 Please let me know what you think.

**Comment by stdevel** [comment]
Looks good to me!

**Comment by maximiliankolb** [comment]
Is "Ubuntu ESM" more is less identical to Ubuntu Pro? Or is it a subset? Should we somehow mention "Ubuntu Pro" next to ESM?
