### ISSUE TITLE
We need another attribute for example FQDN in the doc

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#3]
Hey, 

I was reviewing the html version of the Foreman guide and see throughout 

satellite.example.com

This is the standard we use in all the Satellite docs for a Fully Qualified Domain name that the user needs to substitute for their FQDN when they follow the instructions. 

It should render in the code examples for Foreman as 

foreman.example.com

**Comment by melcorr** [comment]
Ori Rabin pointed out RHEV oVirt etc so we will have to make a list of all the upstream-downstream variations and acronyms also

**Comment by lzap** [comment]
For others we could probably use some generic name like `server.example.com`. But a good point.

**Comment by melcorr** [comment]
@lzap This will be resolved with the large PR: 

from the proposed attributes.adoc file 

:foreman.example.com: satellite.example.com

**Comment by lzap** [comment]
Ok shall we close this one than once merged.
