### ISSUE TITLE
Attributes not rendering properly in code examples

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#31]
I noticed this while working on the VMware content. On preview, the attributes are visible rather than the values. 

I can see it throughout the Libvirt chapter also. 

Any idea why this isn't working?

**Comment by lzap** [comment]
Isn't this just missing subs attributes? Compare:

```
[options="nowrap" subs="+quotes"]
----
# ls {VariableName}
----
```

to

```
[options="nowrap" subs="+quotes,+attributes"]
----
# ls {VariableName}
----
```

**Comment by melcorr** [comment]
I'm pretty sure they have both and are still not rendering.

**Comment by lzap** [comment]
Found the issue, we must avoid dot in the attribute names.

**Comment by lzap** [comment]
https://github.com/theforeman/foreman-documentation/pull/35
