### ISSUE TITLE
Use "product" instead of "Product"

### ISSUE THREAD

**Issue by apinnick** [theforeman/foreman-documentation#3148]
I propose changing "Product" to "product" so that it is consistent with "repository", "content view", and related terminology.

This change requires updates to the Foreman docs, RHSSG, and Vale linter.

**Comment by ekohl** [comment]
:+1: from me to treat them the same. To me they're all the same because they're [models](https://github.com/Katello/katello/tree/master/app/models/katello)

**Comment by Lennonka** [comment]
:+1: Agreed

**Comment by apinnick** [comment]
[PR](https://github.com/redhat-documentation/supplementary-style-guide/pull/507) to update RHSSG
