### ISSUE TITLE
Create docs around Use custom pre/post snippets for errata templates

### ISSUE THREAD

**Issue by chris1984** [theforeman/foreman-documentation#3157]
@maximiliankolb @sbernhard

Can you make some docs around this new feature?

https://github.com/Katello/katello/pull/11074

**Comment by maximiliankolb** [comment]
Hi @chris1984, sure! Just to confirm: this is basically identical to https://github.com/theforeman/foreman/blob/develop/app/views/unattended/provisioning_templates/finish/kickstart_default_finish.erb#L35 and https://github.com/theforeman/foreman/blob/develop/app/views/unattended/provisioning_templates/finish/kickstart_default_finish.erb#L75 with the main selling point "you can run custom commands without unlocking and editing default templates"?

**Comment by sbernhard** [comment]
Yes

**Comment by chris1984** [comment]
Yeah it is
