### ISSUE TITLE
Remove link: from URLs

### ISSUE THREAD

**Issue by spetrosi** [theforeman/foreman-documentation#342]
Currently, some URLs in the source doc files have a `link:` prefix before them, and some do not. It creates inconsistency. `link:` does not add any value and I suggest removing this prefix from all links at once.

**Comment by maximiliankolb** [comment]
I've created a PR to remove all `link:` prefixes from links and cross references. Is this what you had in mind?

**Comment by spetrosi** [comment]
Hey @maximiliankolb, I have merged your PR. Thank you for resolving this issue!
