### ISSUE TITLE
Broken link in Ansible config guide

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#369]
Distribute SSH keys to enable Smart Proxies to connect to hosts using SSH. For more information, see {ManagihgHostsDocURL}ssh-keys-for-remote-execution-overview_managing-hosts[Distributing SSH Keys for Remote Execution] in the Managing Hosts guide. Foreman runs Ansible roles the same way it runs remote execution jobs.

I will do this if I get a chance.

**Comment by tahliar** [comment]
This issue is fixed by PR #421

**Comment by melcorr** [comment]
Thank you !
