### ISSUE TITLE
Remove TargetVersion

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#374]
I noticed that we have the following:

```
:TargetVersion: 6.8
:TargetVersionMaintainUpgrade: 6.8
```

I can't find any use for these, are these some left-overs? Then lets delete them?

**Comment by melcorr** [comment]
These are very much needed downstream for Satellite upgrade guide instructions. Please do not delete :)

**Comment by lzap** [comment]
Okay that explains it.
