### ISSUE TITLE
Satellite docs is not building at all 

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#38]
[mcorr@mcorr doc-Provisioning_Guide]$ make Build=satellite
asciidoctor -a build=foreman -b xhtml5 -d book -o ../build/doc-Provisioning_Guide/index-foreman.html master.adoc

Any idea what's happening? 

I did a make clean and cannot build any Satellite file.

**Comment by lzap** [comment]
From our README:

To build downstream version perform `make BUILD=satellite`.

And it works, it's case sensitive!

```
[lzap@box guides]$ make BUILD=satellite
cd doc-Provisioning_Guide && make html
make[1]: Vstupuje se do adresáře „/home/lzap/work/foreman-documentation/guides/doc-Provisioning_Guide“
asciidoctor -a build=satellite -b xhtml5 -d book -o ../build/doc-Provisioning_Guide/index-satellite.html master.adoc
```

**Comment by melcorr** [comment]
Thanks
