### ISSUE TITLE
Consider adding more options such as SSL configuration options when describing external database setup

### ISSUE THREAD

**Issue by ehelms** [theforeman/foreman-documentation#404]

**Comment by maximiliankolb** [comment]
Please provide options for "foreman-installer" and requirements for external DB host. @ehelms

**Comment by ekohl** [comment]
From a quick glance I think it should be:
* `--foreman-db-root-cert` (for Foreman)
* `--katello-candlepin-db-ssl-ca` (for Candlepin, Katello-only)
* `--foreman-proxy-content-pulpcore-postgresql-ssl-root-ca` (for Pulp, Katello-only)

We only document connecting to a single PostgreSQL server, so these should all point to the same file.

AFAIK we only document remote DBs for project servers, not for content proxies. If we do, the Pulp option is the only one that applies.

**Comment by maximiliankolb** [comment]
triage: This is part of the Installing Foreman guide.

**Comment by ekohl** [comment]
In particular:
https://github.com/theforeman/foreman-documentation/blob/9a75901ddb566aebe80a30864d2ef597bc4063db/guides/common/modules/proc_configuring-satellite-to-use-external-databases.adoc#L33-L44
