### ISSUE TITLE
Katello API Guide

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#428]
If we were to generate the Katello API guide following the normal process, can we host it over here without too much bother? 
Could we just drop the necessary files into /web/ 
Any idea @lzap @ehelms ?

**Comment by melcorr** [comment]
cc @jjeffers

**Comment by lzap** [comment]
I think that API guides must be generated from git checkout or production installation, so we cannot do this via GH Action easily. So probably some manual process? I haven't done that before.

**Comment by melcorr** [comment]
@lzap yeah my idea, unless you folks can come up with a better one, would be to generate in the normal place then host here. 
It should not be too much work, do you think?

**Comment by lzap** [comment]
Yeah no problem as long as someone teach me how to build it, I can do that easily.

**Comment by ekohl** [comment]
I think @evgeni has some experience with running installations inside GHA. Perhaps he has some advice.

**Comment by evgeni** [comment]
Yeah, the advice is: don't ;)

More seriously, what do you need? The apipie HTML output? (like it is today on https://theforeman.org/api/2.3/ and https://theforeman.org/plugins/katello/3.18/api/index.html?)

**Comment by melcorr** [comment]
If docs.theforeman.org is going to be the single source of Foreman and Katello docs, we would need to host API docs also  ?

**Comment by jjeffers** [comment]
Rather than generating the apipie HTML output in this project, would a viable alternative be to provide PRs with the that HTML output for each new version of Katello?

**Comment by evgeni** [comment]
> If docs.theforeman.org is going to be the single source of Foreman and Katello docs, we would need to host API docs also ?

I don't disagree with *that*. But the title says "guide" -- I don't know if we have any *guide* at all. For the generated api docs: I'd not re-build them on every re-deployment of f-documentation, that'll be painful (and slow).

**Comment by lzap** [comment]
For the record, here is an effort I started on this: https://community.theforeman.org/t/proposal-move-apidocs-from-git-to-infra-web/23059
