### ISSUE TITLE
Foreman/Katello upgrade guides

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#433]
We did not migrate the [Satellite Upgrade Guide](https://access.redhat.com/documentation/en-us/red_hat_satellite/6.8/html/upgrading_and_updating_red_hat_satellite/index) to the upstream because there was a lack of knowledge as to how valuable this would be. )

For Katello 4.0, we need to provide an upgrade guide. 
When we complete the migration from old Foreman docs to new, we'll also need to provide a Foreman Upgrade guide. 

At the moment, this is the 3.18 Katello guide: 
https://theforeman.org/plugins/katello/3.18/upgrade/index.html 
https://theforeman.org/plugins/katello/3.18/upgrade/smart_proxy.html
https://theforeman.org/plugins/katello/3.18/upgrade/clients.html

Here are the Foreman guides: 
https://theforeman.org/manuals/2.3/index.html#3.6Upgrade
For Smart Proxy, I'm really unsure. 

The content of these guides are markedly different from the Satellite guide. 
Is there content from the Satellite upgrade guide that is worth migrating upstream? Would Foreman/Katello users benefit from sections, parts etc? 
Or should I just I create separate guides for Foreman and Katello upgrade scenarios that don't track with the downstream? 
Or should I just add the upgrade content as a chapter in the Installation guides like they are in the existing docs? 

I would appreciate your opinion.

**Comment by lzap** [comment]
I think that the Satellite upgrade guide is the most elaborate and a good strategy could be to upstream it. Both Katello and Foreman upgrade instructions are quite short, essentially just "yum update" and "foreman-installer" with few remarks here and there. For both Katello and Foreman we need to implement some if statements to hide irrelevant contents. Example: `foreman-rake katello:upgrade_check` is only relevant for Katello and Satellite scenarios.

**Comment by jlsherrill** [comment]
+1 lets migrate that

**Comment by melcorr** [comment]
This guide is now upstream!
