### ISSUE TITLE
Add section to readme explaining logic of the way the guides are currently put together

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#435]
After a conversation with @maximiliankolb yesterday, it became clear that it could be easy to provide contributors with further direction as to where their content is best placed. 

For example, there was some attempt to apply logic to the Satellite guides, 

The administering Foreman guide is intended to contain content that is admin-level on Foreman 

Managing Hosts in Foreman guide is intended to contain content that is actionable on a host level 

Provisioning guide is intended to provide end to end scenarios for all types of provisioning in Foreman, including compute resources. 

In the past, these guides were often bundled together. For example, the Installation guide was an Installation and Upgrade guide for both Foreman and Smart Proxy. Separating them out allowed us to refine the content and be very specific for each scenario. 

Dirk Goetz, and Marek Hulan, among others have suggested that we separate out each configuration option. I am +1 to this. It's just to find the time. 

For now, at least an intro to how to find where best to submit your content, would be helpful.

**Comment by Lennonka** [comment]
@maximiliankolb will add a note to the README about docinfo.xml

**Comment by Lennonka** [comment]
Thank you, Max!
