### ISSUE TITLE
Add content from Troubleshooting PR to Admin guide logs chapter

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#458]
Add the content from this PR: 

https://github.com/theforeman/foreman-documentation/pull/420

Here: 

https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#chap-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Logging_and_Reporting_Problems

I don't have time to do this week, but will do soon!

**Comment by Lennonka** [comment]
This has been resolved and the related content had been improved since then.
