### ISSUE TITLE
Review missing CLI steps in Provisioning Guide

### ISSUE THREAD

**Issue by tahliar** [theforeman/foreman-documentation#459]
Some CLI "procedures" in the Provisioning Guide just say things like "The compute profile CLI commands are not yet implemented in {ProjectName} {ProductVersion}." 

However, those sentences have been there for a very long time and may be outdated. 

At some point we should review those sections and add CLI steps if they are now available.

**Comment by melcorr** [comment]
@tahliar if you're ever bored and want to link to which sections those CLI commands are missing, I can hunt down the person who would know! Thank you!

**Comment by tahliar** [comment]
@melcorr looks like it's all related to compute profiles:

* 2.15. Creating Compute Profiles
* 13.3. Adding OpenStack Details to a Compute Profile
* 14.5. Adding Amazon EC2 Details to a Compute Profile

**Comment by adamlazik1** [comment]
redmine issue: https://projects.theforeman.org/issues/20538

**Comment by Lennonka** [comment]
Hammer reference: https://access.redhat.com/documentation/en-us/red_hat_satellite/6.14/html/hammer_cli_guide/reference#hammer-compute-profile

**Comment by asteflova** [comment]
For `TW uni course` students: Estimated effort -- L.

**Comment by Marekys** [comment]
I would like to work on this issue
