### ISSUE TITLE
Create procedure for multi-homed Foreman Server/Smart Proxy Servers

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#478]
The standard practice is to have a separate provisioning network, Foreman is designed to do this but it looks like our users do struggle:

https://community.theforeman.org/t/configuration-to-install-one-machine-on-its-first-interface-by-dhcp-and-then-be-static-for-another-network/22730

We need to write such procedure, maybe do a YT video as well.

**Comment by melcorr** [comment]
@lzap This would be a nice opensource.com article in my opinion.

**Comment by maximiliankolb** [comment]
triage: to revisit; for Avital to decide to work on it or not.

Maybe docs.theforeman.org is not the best place; alternative ideas: blog article or YT video.
