### ISSUE TITLE
Iron out eth1 in the Networking chapter (4)

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#5]
The chapter tells to use eth1 for nameserver however I don't see a reason to do so. Actually we recommend to deploy Satellite on a single NIC hosts, that is the very opposite. Need to fix this.

**Comment by melcorr** [comment]
@lzap this seems important. Perhaps we can revisit it soon so I can better understand the problem and fix?

**Comment by ekohl** [comment]
I think this refers to https://docs.theforeman.org/nightly/Installing_Server/index-katello.html#configuring-dns-dhcp-and-tftp_foreman and still looks relevant. I think this is recommending to drop this from the installer command:
```
--foreman-proxy-dns-interface eth0 \
--foreman-proxy-dhcp-interface eth0 \
--foreman-proxy-dhcp-additional-interfaces eth1 \
--foreman-proxy-dhcp-additional-interfaces eth2 \
```

As a maintainer of the installer I think I agree with this and we should review all instances where multiple interfaces are specified.
