### ISSUE TITLE
Host registration changes in 2.5 version

### ISSUE THREAD

**Issue by stejskalleos** [theforeman/foreman-documentation#513]
**Changes in templates**
`Linux registration default` template is now `Host initial configuration` (kind: `host_init_config`) and it is automatically assigned to every OS (so no need to set it manually). 
Template that is assigned to the OS can be set in the settings the same way as default global registration template

**API**
There is new API endpoint `/registration_commands` for generating command (and that goes with `hammer` support too)

**Form - New fields**
* `Install packages` - Install packages on the host when registered. Can be set by `host_packages` parameter
* `Repository` - A repository to be added before the registration is performed. It can be useful to e.g. make the subscription-manager packages available for the purpose of the registration. For Red Hat family distributions, this should be the URL of the repository, e.g. 'http://rpm.example.com/'. For Debian OS families, it's the whole list file content, e.g. 'deb http://deb.example.com/ buster 1.0'.
* `Repository GPG key URL` - If packages are GPG signed, the public key can be specified here to verify the packages signatures. It needs to be specified in the ascii form with the GPG public key header.
* `Lifecycle environment` (Satellite only) - 
* `Ignore errors` (Satellite only) - Ignore subscription manager errors
* `Force` (Satellite only) - Remove any `katello-ca-consumer` rpms before registration and run subscription-manager with `--force` argument.

**Form - Other changes**
* Some fields now inherits value from Host group field: `Operating system`, `Activation keys` & `Life cycle environment`
* JWT used for authentication is now limited to the scope of registration only (you can't use it anymore on other API endpoints`
* JWT expiration can be set to unlimited
* Extending form - Now with React.js components, See https://github.com/theforeman/foreman/blob/develop/webpack/stories/docs/slot-and-fill.stories.mdx

I hope that I didn't forget anything :)

**Comment by melcorr** [comment]
Hey @stejskalleos 
Thanks for writing this up. 
Can I just check with you - will you add a PR with these doc updates also?
