### ISSUE TITLE
Is displaying the {ProductVersion} necessary?

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#537]
Hi everyone.

Is there a reason to display `{ProductVersion}` in some cases after `{ProjectName}`?

I can totally understand this concept for links to the Red Hat Documentation as well as in the context of upgrading Foreman/SmartProxy.

In other cases, I am unsure what's the benefit:

`git grep -i -n "{ProductVersion}"`:

```
...
guides/doc-Provisioning_Guide/topics/Bare_Metal.adoc:4:There are four main ways to provision bare metal instances with {ProjectName} {ProductVersion}:
guides/doc-Provisioning_Guide/topics/Virt-VMWare.adoc:25:For VMware vCenter Server version {ProductVersion}, set the following permissions:
...
```

Thanks.
Maximilian.

**Comment by melcorr** [comment]
Well, in these examples not, but in the upgrade guide, it is necessary for sure. 
The second example there looks to me like some tasty sed :-)

**Comment by lzap** [comment]
I think historically the product name was Red Hat Satellite 6 but I believe this was rebranded now just to Red Hat Satellite so we can perhaps completely remove these (except from upgrade guide)? Go ahead.

**Comment by maximiliankolb** [comment]
Done as #540 has been merged.
