### ISSUE TITLE
Document efibootmgr_netboot

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#61]
Foreman workflow is based on setting all managed servers to boot from network and then from HDD, therefore Foreman can decide if to reinstall OS or exit PXE and boot from secondary device (HDD). But in EFI world, this does not work reliably - OS installer usually creates a new EFI entry as the first, so after restart the server boots into the new system. The issue is reprovisioning - when the host is put into build mode in Foreman and the server is restarted, it will ignore this and boot into the old system.

The solution is to modify EFI boot order back to boot from previous entry, assuming that the first entry was PXE/iPXE. There is a proposal snippet 25 included from provisioning template, but since this does not work reliably (e.g. in libvirt this fails) the proposed solution is opt-it only via “efi_bootentry” host parameter:

    When set to “previous” after OS installation the new entry will be removed from top and appended as the last entry.
    When set to arbitrary text, this will be used as input to “grep -E” as a regular expression to find boot entry to set as the first. Every EFI firmware vendor names PXE/HTTP Boot entries differently, so there is no standard and a regular expression for all hosts must be created unfortunately.
    No action is taken when not set (host will boot from HDD everytime).

https://community.theforeman.org/t/discovery-ipxe-efi-workflow-in-foreman-1-20/13026

We should describe this in docs. This is a common issue across all UEFI provisioning workflows and the snippet should help users to workaround the problem.

https://github.com/theforeman/community-templates/pull/557/files

**Comment by maximiliankolb** [comment]
@jloeser Do you know if the tutorial by lzap in the Foreman Community Forum can be salvaged for the docs? Do you know if you can rebuild hosts in Foreman that are provisioning over EFI?

**Comment by jloeser** [comment]
@maximiliankolb The merged PR (https://github.com/theforeman/foreman-documentation/pull/56) referenced here has nothing to do with this topic.

But there is https://github.com/theforeman/foreman-documentation/commit/9d4331d634bbe1dca34d8dafe55ef93f3c2b874e which is already part of our documentation (https://docs.orcharhino.com/or/docs/sources/guides/centos/provisioning_hosts/introduction.html#Network_Boot_Provisioning_Workflow_provisioning).

Is this enough or do we need a more detailed explanation?

**Comment by maximiliankolb** [comment]
Thanks for checking the existing docs. This seems good enough; closing this issue for now.
