### ISSUE TITLE
docs.theforeman.org guides page is messy

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#646]
We could do with a better layout for our new guides page. 
For example: 
https://docs.theforeman.org/nightly.html

We should group them together in a logical way. 

First 

installation guides (Foreman)
installation guides (Katello)

Then guides arranged in an order that we think most logical, perhaps with a brief description of the contents of the guide, what the user can expect to find in the guide beneath.

**Comment by lzap** [comment]
Should we not mention Foreman and Katello and rather recommend to install Katello as the default installation for everybody?

**Comment by ekohl** [comment]
No, I don't think we should recommend Katello for everyone. I think the system requirements would scare away a lot of (potential) users. In https://github.com/theforeman/foreman-documentation/pull/678 I've at least given some guidance so they can make a more informed decision.

IMHO we should continue to work to making Katello a real Foreman plugin in the sense that you can add it after the fact. The platform team is working on that, but it's a long road.

**Comment by ekohl** [comment]
By now we've trimmed down the list of guides. I still think it can be improved, but I think it's no longer messy. Going to close this for now.
