### ISSUE TITLE
Add info about monitoring to an external PCP instance

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#65]
After we migrate Monitoring Guide this must be the very first change. We want to allow PCP running on RHEL7 to send data over network to PCP running on RHEL8 to leverage modern Grafana visualization software.

**Comment by melcorr** [comment]
All of this is external to Satellite so we need to focus on how to retrieve this information via Satellite. 

Where can I find more information/notes about that?

**Comment by lzap** [comment]
Sorry what?

**Comment by melcorr** [comment]
You're talking about this, aren't you: 

https://bugzilla.redhat.com/show_bug.cgi?id=1654815

And being able to work with this in Satellite? 

I suppose perhaps I am not sure what you're talking about. However we won't be adding any docs relating to PCP on RHEL7. They are for the RHEL team to figure out. Anything we add has to be instructions relating directly to Satellite.

**Comment by lzap** [comment]
Well it's related, but it's something else. This is a note for me, sometime in late 2020 I should work on this.

**Comment by ekohl** [comment]
#2407 will replaced the whole monitoring guide, so closing
