### ISSUE TITLE
Admin guide adapation: 5.4.5. Creating a Complete Permission Table - foreman-rake console

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#685]
As part of #676, feedback from @ekohl about Katello v Foreman-EL scenarios 

There is this section in the Admin guide: 5.4.5. Creating a Complete Permission Table 

https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#sect-Administering-Users_and_Roles-Creating_and_Managing_Roles

@ekohl made the following comment about that content: 

>Chapter 5.4.5. why in gods name do we recommend users to use foreman-rake console? If anything, we 
> should create a rake task in upstream and recommend something like foreman-rake permissions:table. >Also, yum install tfm-rubygem-foreman* is dangerous. It installs all plugins which are available, which is a lot! >You are extremely likely to break your installation with no way back.

I would like to get this addressed, but need alternative steps. If someone can point me towards the person who could help me resolve it?!

I could address it in #684 if this is answered sometime soon.

**Comment by ekohl** [comment]
I think it would be best to open a Redmine issue and submit the code to Foreman upstream. Would you mind opening that issue?

**Comment by melcorr** [comment]
Code? Is this not just a docs change?

**Comment by melcorr** [comment]
I understand now. The power of taking a step back. I will file a redmine. Sorry for the confusion. Will close this and link to the redmine once I do it.

**Comment by melcorr** [comment]
https://projects.theforeman.org/issues/33334 
I tried to capture the point here. Feel free to update/correct.

**Comment by ekohl** [comment]
Thanks!
