### ISSUE TITLE
Add steps for migrating from internal to external DBs for RHEL 8 systems

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#688]
As part of work to complete #684, it is noted here https://github.com/theforeman/foreman-documentation/pull/684#discussion_r694821580 that we also need to develop instructions for migrating from internal databases to external databases for RHEL 8 systems. 

https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#migrating-from-internal-databases-to-external-databases_admin

**Comment by ekohl** [comment]
This has been done by now.
