### ISSUE TITLE
Admin guide, chapter 8  Backing Up Foreman server and Smart Proxy server for Foreman-el 

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#693]
Comments from @ekohl: 

"Mention of /root/ssl-build and various other directories makes it Katello-only. "

Here is the passage in question: 

`A backup contains sensitive information from the /root/ssl-build directory. For example, it can contain hostnames, ssh keys, request files and SSL certificates. You must encrypt or move the backup to a secure location to minimize the risk of damage or unauthorized access to the hosts.`

It is mentioned a total of three times, in the above paragraph and in the du example: 

https://docs.theforeman.org/nightly/Administering_Red_Hat_Satellite/index-foreman-el.html#estimating-the-size-of-a-backup_admin

If this is the only adjustments that would be needed for the information to be of use to vanilla Foreman EL scenarios, I hope I can find someone that can provide the information.

**Comment by ekohl** [comment]
I'll consider https://github.com/theforeman/foreman-documentation/issues/1874 more recent so closing as a duplicate.
