### ISSUE TITLE
HTTP boot installer remark

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#71]
Once we get there (I think this is still undocumented) we need to make sure these params are present:

    foreman-installer --foreman-proxy-httpboot=true --foreman-proxy-http=true --foreman-proxy-httpboot-listen-on=both

**Comment by ekohl** [comment]
The `--foreman-proxy-httpboot-listen-on=both` option matches the default.

`--foreman-proxy-httpboot=true` should not be needed if `--foreman-proxy-fttp=true` is passed (default). If you want to be explicit, then you should add that too. Otherwise I'd simplify it to:
```
foreman-installer --foreman-proxy-http=true
```

**Comment by melcorr** [comment]
Is this now resolved: 

https://docs.theforeman.org/master/Provisioning_Guide/index-foreman.html#creating-hosts-with-uefi-http-boot-provisioning_provisioning

**Comment by lzap** [comment]
Yes thank you.
