### ISSUE TITLE
Broken link in Ansible docs from registration docs updates

### ISSUE THREAD

**Issue by melcorr** [theforeman/foreman-documentation#715]
Hey @stejskalleos 
If you get a minute, can you help me figure out how I need to update the following link: 

https://docs.theforeman.org/2.5/Configuring_Ansible/index-foreman-el.html#ssh-keys-for-remote-execution-overview_ansible

"For new Foreman hosts, you can deploy SSH keys to Foreman hosts during registration using the global registration template. For more information, see Registering a Host to Foreman Using the Global Registration Template." - The link points to nothing, any idea to where it should be pointed? https://docs.theforeman.org/2.5/Managing_Hosts/index-foreman-el.html#registering-a-host-to-project-using-the-global-registration-template_managing-hosts

It is present in 2.4 docs: https://docs.theforeman.org/2.4/Managing_Hosts/index-foreman-el.html#registering-a-host-to-project-using-the-global-registration-template_managing-hosts

**Comment by stejskalleos** [comment]
@melcorr https://github.com/theforeman/foreman-documentation/pull/716

**Comment by melcorr** [comment]
Thank you!
