### ISSUE TITLE
Add info about expected interface names

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#73]
Foreman expects network devices to follow some naming scheme in order to detect them correctly. For example if bond is named "mybond0" it will not be correctly detected and host registration (through puppet, ansible or rhsm) will fail. It must be named "bondN" where N is a number. Similar rules apply for others. We need to out this into some guide.

**Comment by maximiliankolb** [comment]
triage: @Lennonka Please check if we can a) close this issue or b) what to change exactly. current issue is unclear.

**Comment by maximiliankolb** [comment]
Then I assume we can close this issue:

````
$ rg bond0
guides/common/modules/proc_adding-a-bonded-interface.adoc
16:Bonded interfaces use IDs in the form of *bond0* in the *Device Identifier* field.
53:--interface="identifier=_bond0_, ip=_My_IP_Address_2_, type=Nic::Bond, mode=active-backup, attached_devices=[_My_NIC_1_,_My_NIC_2_], managed=true, domain_id=_My_Domain_ID_, subnet_ [... 0 more matches]
$ rg -i my_bond
# no results
````

@swadeley OK for you?

**Comment by swadeley** [comment]
You could make it stronger:
Bonded interfaces must use IDs in the form  "bondN" , where N is a number, the *Device Identifier* field.

Up to you, I don't know how many people get this wrong.
