### ISSUE TITLE
Two asciidoc attributes in one anchor/link

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#746]
Run `git grep "{.*{" guides | grep 'id='`:

    guides/common/modules/proc_configuring-repositories-el.adoc:1:[id="configuring-repositories-el-{distribution-major-version}-{package-manager}"]
    guides/common/modules/proc_installing-server-packages-el.adoc:1:[id="configuring-foreman-repositories-el-{package-manager}-{context}"]

I've fixed all other instances in https://github.com/theforeman/foreman-documentation/pull/741 > See 8c364cbd829864547e4be96d6a4a0b8901b7157d & https://github.com/theforeman/foreman-documentation/pull/741#pullrequestreview-778895635

FYI @melcorr

**Comment by melcorr** [comment]
Thanks @maximiliankolb  - I will take a look .

**Comment by ekohl** [comment]
Is this still an issue?

**Comment by maximiliankolb** [comment]
It's specific to RHs framework to build/deliver docs. I don't know.
