### ISSUE TITLE
Remove 'migrating_pulp_content' section for Katello 4.2 and onwards

### ISSUE THREAD

**Issue by ianballou** [theforeman/foreman-documentation#760]
Currently, the Katello 4.2 docs mention a `prep-7.0-upgrade` which doesn't exist. It's caused by `{foreman-maintain} prep-{TargetVersion}-upgrade` in `guides/doc-Upgrading_and_Updating/topics/migrating_pulp_content.adoc`.

We won't need that again, so we can delete the pages instead of just hiding the content.

**Comment by lzap** [comment]
Please file a PR, thank you :-)

**Comment by lzap** [comment]
I have just realized Katello docs are moved here, feel free to use GH issues. :-)

**Comment by melcorr** [comment]
I think this is done. https://docs.theforeman.org/3.1/Upgrading_and_Updating/index-katello.html
I hadn't spotted the issue.
