### ISSUE TITLE
Add docs about no direct HTTPS support for Katello versions from 4.0 to 4.2

### ISSUE THREAD

**Issue by ianballou** [theforeman/foreman-documentation#790]
https://bugzilla.redhat.com/show_bug.cgi?id=2012279

Katello 4.1 does not directly support syncing through HTTPS proxies due to the change to Pulp 3.  A user can get around this by setting up an HTTP proxy that forwards traffic to the HTTPS one.

**Comment by lzap** [comment]
I see multiple issues created by you guys, so can I assume you are going to use GH issues to track Katello? That's completely fine by me.

**Comment by ekohl** [comment]
Given these old Katello versions are end of line, can this be closed now. AFAIK current versions do have it.
