### ISSUE TITLE
Clean up guides/doc-Configuring_Load_Balancer/topics/Registering_Clients.adoc

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#829]
This file should be cleaned up and made more upstream friendly. We should also remove `Registering Clients Manually with katello-ca-consumer rpm` in our devel branch if it's deprecated.

**Comment by asteflova** [comment]
Hi @maximiliankolb while looking at issues tagged as `good first issue`, I ran into this one. Everything under doc-Configuring_Load_Balancer seems to have been modularized and moved to `common/modules/`. Can I assume that the file has been cleaned up as requested? Is there anything left to do to fix this issue?

**Comment by maximiliankolb** [comment]
Yes, this is no longer an issue. See https://docs.theforeman.org/nightly/Configuring_Load_Balancer/index-katello.html#Registering_Clients_to_the_Load_Balancer_load-balancing
