### ISSUE TITLE
Switch to CC BY-SA 4.0

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#885]
Hello, before I pushed the content into github, I checked with Red Hat legal. Together with confirmation, I got a comment from Richard Fontana that we should consider upgrading the license. I totally forgot about this, so at least creating a ticket in case someone wants to jump into this.

Quote from Richard:

> 1.  I would recommend using this opportunity to modernize the
> documentation license (which should be the same for upstream and
> redhat.com). CC BY-SA 3.0 is kind of an outdated license at this point
> and there's an odd addendum in our legal notice that would not be
> needed if we switched to CC BY-SA 4.0 -- very similar to CC BY-SA 3.0
> but somewhat improved.

**Comment by ekohl** [comment]
@apinnick has started to look at the licensing situation and will consider this.

**Comment by apinnick** [comment]
I got the same message from Richard (I asked before I knew about this issue). I agree that we should upgrade. Oddly enough, the d/s RH docs still use CC BY-SA 3.0 and refer to the Shadowman logo. I wonder whether RH Legal plans to update the notice. I will create a PR to update the site license.
