### ISSUE TITLE
There is no prep-satelliteversion-upgrade subcommand for foreman-maintain

### ISSUE THREAD

**Issue by Areyus** [theforeman/foreman-documentation#895]
The Katello upgrade docs at docs.theforeman.org state in section [2.1.1 step 2](https://docs.theforeman.org/nightly/Upgrading_and_Updating/index-katello.html#preparing_to_migrate_pulp_content) that you should execute `foreman-maintain prep-6.10-upgrade (this is from the 2.5 docs, replaced by 7.0 in the 3.0 docs or nightly in nightly docs respectively).
However, this subcommand does not exist in opensource Katello installations.

This was originally reported [on the forum by bradawk](https://community.theforeman.org/t/bug-report/26424).

**Comment by melcorr** [comment]
Thank you for reporting this @Areyus 
I will find someone to remove this :)
