### ISSUE TITLE
Installing Foreman + Katello + Puppet: parameters are missing

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#928]
Hi!

Apparently we have an issue in 3.1 docs regarding the installation of Foreman/Katello with Puppet Server. It looks like some parameters when calling the `foreman-installer` are missing.

[Foreman Community Forum: "Foreman-installer –scenario katello does not install puppet-server"](https://community.theforeman.org/t/foreman-installer-scenario-katello-does-not-install-puppet-server/26664/3).

**Comment by adamlazik1** [comment]
The parameters are now documented: https://docs.theforeman.org/2.4/Provisioning_Guide/index-foreman-el.html#creating-hosts-with-uefi-http-boot-provisioning_provisioning
