### ISSUE TITLE
Unify emphasis for guides

### ISSUE THREAD

**Issue by maximiliankolb** [theforeman/foreman-documentation#954]
Maybe we should unify the emphasis for guides? 

source: https://github.com/theforeman/foreman-documentation/pull/942#discussion_r783929680 

cc @Lennonka 

IMHO low priority, but maybe I can come up with a `find -exec sed` command to take care of this.

"... in the _Administering Foreman Guide_" is correct, everything else is wrong?

**Comment by melcorr** [comment]
Yeah. A guide title should be referenced as you have indicated above. 
Hopefully we can automate the majority of this!

**Comment by melcorr** [comment]
Should we use a variable for the guide names? Then we can add the formatting in there and not depend on people to get it right every time?

**Comment by melcorr** [comment]
Reopening - hit the wrong button.

**Comment by Lennonka** [comment]
Absolutely. The emphasis should include the whole guide title in the same wording as the actual title, otherwise we're confusing the reader a bit. A variable for each guide title sounds like a good idea.

**Comment by Lennonka** [comment]
I'm working on this.

**Comment by Lennonka** [comment]
@melcorr Do we have a go?

**Comment by melcorr** [comment]
I think this is a good step forward. +1

**Comment by Lennonka** [comment]
I've decided to split this task into 2 PRs:

- Phase 1 in #1230 to introduce attributes for guide titles and suggest improvements for guide folders and guide titles wording.
- Phase 2 will apply attributes in title references in the guides themselves.

**Comment by Lennonka** [comment]
@maximiliankolb I could use your help with the script to update the guide references, because we're really tight on schedule. Do you think you could help?

**Comment by Lennonka** [comment]
But that unity does not concern guide titles, only UI labels. In my opinion, we don't have to wait.

**Comment by Lennonka** [comment]
@melcorr You most certainly are not :))

**Comment by maximiliankolb** [comment]
> @maximiliankolb I could use your help with the script to update the guide references (Phase 2), because we're really tight on schedule. Do you think you could help?

Yes, I can help for sure on Monday. If it's just 'replace X with Y', then it should be very doable.

**Comment by Lennonka** [comment]
Absolutely, just a tip to observe several patterns as we've discussed earlier.

**Comment by maximiliankolb** [comment]
can you assemble a short "old" vs "new" list? Or tell me where I can find it/what's it gonna look like? one or two examples might be sufficient.

**Comment by Lennonka** [comment]
Pattern samples for Phase 2:

OLD
- `<URL with an anchor and a title> in the _Managing Hosts_ guide`
- `[Ss]ee the {ManagingHostsDocURL}[_Managing Hosts_] guide`

NEW
- `<URL with an anchor and a title> in _{ManagingHostsDocTitle}_`
- `[Ss]ee {ManagingHostsDocURL}[_{ManagingHostsDocTitle}_]`

Observe for each guide/title. Also, the words "guide" and the "the" article might be present or absent, depending on each occurence. And the patterns may be potentially more complex.

**Comment by Lennonka** [comment]
@maximiliankolb Will that^^ suffice or would you like smoe more? :)

**Comment by maximiliankolb** [comment]
@Lennonka  Yes, thanks, that'll do for now. I am already working on it, but there's much much more variations for a single DocURL ... I will share my draft later today.

**Comment by Lennonka** [comment]
I'm wondering if we should mention the conventions that arise from this issue somewhere? Or are we good to close it?

**Comment by maximiliankolb** [comment]
Good idea, I will create a small PR to extend our conventions!
