### ISSUE TITLE
Update navigation to highlight build flavors

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman-documentation#959]
In the past I've mentioned this, but now that the site is completely reworked we're actually in a position to implement this. My proposal is to evolve what we have now (post nanoc PR merge) in essentially 3 steps:

First of all, there's the version (nightly, 3.1, 3.0, etc). That's already there today and I like how it's implemented.

The next level would be the build flavor. Today there are 2 drop downs, but we have 3 flavors (foreman-el, foreman-deb and katello). That's why I'm proposing to add a new filter: the build flavor. I'd suggest it's implemented exactly like the version filter as a drop down.

Then the last step is to select the guide. This is essentially what's now in the `Foreman documentation` and `Katello documentation`. I'd propose to rename it to `Guides` with the available guides in the combination of version + flavor.

This will solve that we don't have certain guides available for some combinations and give a more unified feeling.

**Comment by lzap** [comment]
Sure Guide word looks narrower than Documentation and therefore we could save some screen space to have three columns.

**Comment by ekohl** [comment]
I now consider this resolved
