### ISSUE TITLE
Remove "Red Hat" from directories

### ISSUE THREAD

**Issue by lzap** [theforeman/foreman-documentation#970]
This needs to be communicated with the Red Hat team so they know when their downstream build breaks. I would like ask @melcorr to arrange this. I can do the change when requested but merging should be synchronized with RHD.

```
$ ls guides/ | grep Red
doc-Administering_Red_Hat_Satellite
doc-Installing_Proxy_on_Red_Hat
doc-Installing_Server_on_Red_Hat
```

**Comment by ekohl** [comment]
> doc-Installing_Proxy_on_Red_Hat

Note that here we also have `doc-Installing_Proxy_on_Debian` but the content is exactly the same. Same for Installing_Server. So these 2 should be merged. It may need to be cherry picked since the website can't link to different documents for different versions.

**Comment by ekohl** [comment]
Oh, another thought: we can actually introduce the new location as another copy. Then drop the old guides once everyone's ready. It's just using common fragments so it's just the assembly, which is rather static.

**Comment by melcorr** [comment]
So, the optimal time to do this would be now and cherry-pick back to 3.1, because those books have not been made yet for Satellite 7 in the downstream. 

This would only ever break anything for them if they had already fed the documentation guide URLs into the publication tool, Pantheon. 
@Lennonka - there's no 7 branch for Satellite docs yet, is there?

**Comment by ekohl** [comment]
:+1: for that. Due to nav.js we'd also need to implement it in all other branches. I'd suggest to implement it there as additional guides without removing the `_on_$os` variants.

**Comment by melcorr** [comment]
OK, that's a bigger job but not difficult all the same.

**Comment by ekohl** [comment]
I opened https://github.com/theforeman/foreman-documentation/pull/1006 which I think implements this.
